# Generated by Django 3.2.6 on 2021-08-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/deafault.jpeg', upload_to='profile_pics'),
        ),
    ]
