# Generated by Django 3.2.6 on 2021-08-29 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
