# Generated by Django 3.2.6 on 2021-09-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story_user',
            new_name='user',
        ),
    ]
