# Generated by Django 3.2.6 on 2021-08-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_comment_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
