# Generated by Django 3.2.6 on 2021-09-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='story',
        ),
    ]
