# Generated by Django 3.2.6 on 2021-09-07 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_rename_story_user_story_user'),
        ('social', '0008_delete_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='story_pics')),
                ('story_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_post', to='landing.profile')),
            ],
        ),
    ]
