# Generated by Django 3.2.6 on 2021-09-07 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_rename_story_stori'),
    ]

    operations = [
        migrations.AddField(
            model_name='stori',
            name='posted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
